# Generated by Django 3.2.6 on 2021-10-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=18)),
                ('obs', models.TextField(blank=True, null=True)),
                ('cadastrado', models.DateTimeField(auto_now_add=True)),
                ('finalizado_done', models.BooleanField(default=False)),
            ],
        ),
    ]
